# Copy package files first for better layer caching
COPY --chown=$USER_ID:$GROUP_ID package*.json ./
COPY --chown=$USER_ID:$GROUP_ID bun.lock ./

# Install dependencies
RUN ~/.bun/bin/bun i --frozen-lockfile

# Copy application code
COPY --chown=$USER_ID:$GROUP_ID . .

RUN chown -R $USER_ID:$GROUP_ID /tmp/yellow; mkdir -p /tmp/yellow; chown -R $USER_ID:$GROUP_ID /tmp/yellow ;chmod 1777 /tmp/yellow; echo ok; mkdir -p /var/log/yellow; chown -R $USER_ID:$GROUP_ID /var/log/yellow ;chmod 1777 /var/log/yellow

